import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  MapPinned, Compass, FileText, ClipboardList, SearchCheck, Wallet,
  BarChart3, ShieldCheck, ArrowRight, Lock, Fingerprint, ScrollText,
  CheckCircle2, ChevronDown, ChevronUp, Phone, Mail, MapPin,
  Users, Clock, Award, Globe, Star, Building2, FileCheck, AlertCircle,
  ArrowRightLeft, Upload, Bell,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth";
import { cn } from "@/lib/utils";
import PublicNav from "@/components/PublicNav";
import StickyFooter from "@/components/StickyFooter";
import NewsFlash from "@/components/NewsFlash";
import pb from "@/lib/pocketbaseClient";
import apiServerClient from "@/lib/apiServerClient";

const HERO = "https://images.hostinger.com/be655138-806c-4137-85f0-2f9e6569c1a8.png";
const SURVEY = "https://images.hostinger.com/1cf01faf-bfa6-4262-bcfa-179cc06f71ff.png";
const CITIZEN = "https://images.hostinger.com/a7dbec65-2e55-4a59-a87e-e8f967f65d44.png";

const SERVICES = [
  { icon: MapPinned, title: "Land Registration", desc: "Register land parcels with full ownership records, parcel numbers, and official certification." },
  { icon: SearchCheck, title: "Title Search & Verification", desc: "Verify ownership, check encumbrances, and obtain official title search certificates instantly." },
  { icon: FileText, title: "Document Management", desc: "Securely store and manage all land documents — deeds, indentures, site plans, and certificates." },
  { icon: ClipboardList, title: "Land Transfer", desc: "Process ownership transfers with full audit trail, approval workflows, and certification." },
  { icon: Compass, title: "Cadastral Survey", desc: "Commission and manage professional land surveys with GPS coordinates and boundary data." },
  { icon: Wallet, title: "Payment Processing", desc: "Process land-related payments securely. Finance Officers manage invoices and receipts for all land transactions." },
];

const FEATURES = [
  { icon: MapPinned, title: "Automatic Land IDs", desc: "Every parcel receives a unique TeNDA-PPD-[COMMUNITY]-XXXX identifier, assigned automatically during registration." },
  { icon: FileCheck, title: "Separate Multiple-Land Records", desc: "Owners with several lands get an independent parcel record per land — each with its own ID, status, and history." },
  { icon: Building2, title: "Administrative Hierarchy", desc: "Records are organized by Office, Area Council, Community, and Sector for precise scoping and reporting." },
  { icon: ArrowRightLeft, title: "Transfers & Approvals", desc: "Formal ownership transfers and a centralized approvals workspace with full audit trails and notifications." },
  { icon: ShieldCheck, title: "Public Land Verification", desc: "Community members verify registered lands through a secure, code-protected public portal — private details stay private." },
  { icon: BarChart3, title: "Reports & Analytics", desc: "AI-powered dashboards, year-on-year trends, and exportable statistics across the entire registry." },
  { icon: Upload, title: "Bulk Import & Export", desc: "Import land records from CSV, XLS, and XLSX; export parcels to CSV, XLS, XLSX, PDF, and SQL." },
  { icon: Bell, title: "Real-Time Notifications", desc: "In-app alerts and SMS keep staff and owners informed at every stage of every transaction." },
];

const STEPS = [
  { num: "01", title: "Create an account", desc: "Contact the District Assembly Administrator to create your staff account." },
  { num: "02", title: "Register your land", desc: "Fill in your parcel details — applicant info, location, sector, and dates." },
  { num: "03", title: "Submit documents", desc: "Upload supporting documents including site plans, deeds, and identification." },
  { num: "04", title: "Review & approval", desc: "Your application moves through Planning, Survey, and Registry review stages." },
  { num: "05", title: "Process application payment", desc: "Finance Officers process the payment invoice generated by the system for your application." },
  { num: "06", title: "Receive certificate", desc: "Download your official land title certificate once approved and registered." },
];

const STATS_STATIC = [
  { key: "parcels", label: "Registered parcels", icon: MapPinned, suffix: "+" },
  { key: "transfers", label: "Land transfers", icon: FileCheck, suffix: "+" },
  { key: "officers", label: "Active officers", icon: Users, suffix: "" },
  { key: "councils", label: "Area Councils served", icon: MapPin, suffix: "" },
];

function AnimatedCount({ value, suffix = "" }) {
  const [display, setDisplay] = React.useState(0);
  React.useEffect(() => {
    if (!value) { setDisplay(value); return; }
    const duration = 1200;
    const start = Date.now();
    const from = 0;
    const to = value;
    const tick = () => {
      const elapsed = Date.now() - start;
      const progress = Math.min(elapsed / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setDisplay(Math.round(from + (to - from) * eased));
      if (progress < 1) requestAnimationFrame(tick);
    };
    requestAnimationFrame(tick);
  }, [value]);
  return <>{display}{suffix}</>;
}

function useLiveStats() {
  const [stats, setStats] = React.useState({ parcels: null, transfers: null, officers: null, councils: null });
  const [error, setError] = React.useState(false);

  const fetchStats = React.useCallback(async () => {
    try {
      const res = await apiServerClient.fetch("/public-stats");
      if (!res.ok) throw new Error("stats request failed");
      const data = await res.json();
      setStats({
        parcels: data.parcels ?? null,
        transfers: data.transfers ?? null,
        officers: data.officers ?? null,
        councils: data.councils ?? null,
      });
      setError(false);
    } catch {
      setError(true);
    }
  }, []);

  // Initial load + periodic refresh (every 60s) + refresh on focus/online.
  React.useEffect(() => {
    fetchStats();
    const interval = setInterval(fetchStats, 60000);
    const onFocus = () => fetchStats();
    window.addEventListener("focus", onFocus);
    window.addEventListener("online", onFocus);
    return () => {
      clearInterval(interval);
      window.removeEventListener("focus", onFocus);
      window.removeEventListener("online", onFocus);
    };
  }, [fetchStats]);

  // Realtime refresh on public collections (parcels, area_councils) so the
  // public counts update immediately when those records change. Private counts
  // (transfers, officers) refresh via the periodic poll above.
  React.useEffect(() => {
    let cancelled = false;
    const trigger = () => { if (!cancelled) fetchStats(); };
    void pb.collection("parcels").subscribe("*", trigger).catch(() => {});
    void pb.collection("area_councils").subscribe("*", trigger).catch(() => {});
    return () => {
      cancelled = true;
      void pb.collection("parcels").unsubscribe("*").catch(() => {});
      void pb.collection("area_councils").unsubscribe("*").catch(() => {});
    };
  }, [fetchStats]);

  return { stats, error };
}

const FAQS = [
  {
    q: "Who can use the Techiman North Land Registry System?",
    a: "The system is for authorized district staff including Planning Officers, Surveyors, Land Registrars, Finance Officers, and District Administrators. Staff accounts are created by the District Assembly Administrator.",
  },
  {
    q: "What documents do I need to register land?",
    a: "You typically need a site plan, Ghana Card identification, proof of ownership (deed/indenture), and any relevant customary documentation. The system supports uploading all document types securely.",
  },
  {
    q: "How long does land registration take?",
    a: "The process typically takes 5–14 days depending on the complexity of the application. Applications with complete documentation and no disputes are processed faster.",
  },
  {
    q: "Is my data secure on this platform?",
    a: "Yes. All data is encrypted with AES-256, access is controlled by role-based permissions, all actions are immutably logged in an audit trail, and multi-factor authentication protects every account.",
  },
  {
    q: "What payment methods are accepted?",
    a: "The system supports recording of Mobile Money, bank transfer, and cash payment methods. All payments are managed by Finance Officers at the district office.",
  },
  {
    q: "What are the Area Councils covered?",
    a: "The system covers Tuobodom, Offuman, Aworowa, Buoyem, and Krobo Area Councils within the Techiman North District.",
  },
];

const COMPLIANCE = [
  { icon: Fingerprint, title: "Ghana Card verified", body: "Every identity is validated against the National Identification number." },
  { icon: Lock, title: "AES-256 encryption", body: "Data encrypted at rest and in transit end-to-end." },
  { icon: ScrollText, title: "Full audit trails", body: "Every transaction and change immutably logged." },
  { icon: ShieldCheck, title: "MFA & RBAC", body: "Multi-factor sign-in and least-privilege role controls." },
];

function LatestNews() {
  const [posts, setPosts] = React.useState([]);
  React.useEffect(() => {
    pb.collection("news_posts").getList(1, 4, {
      filter: 'status="published"',
      sort: "-publishedAt,-created",
      expand: "category",
      requestKey: "landing-news",
    }).then((r) => setPosts(r.items)).catch(() => {});
  }, []);

  if (posts.length === 0) return null;

  return (
    <section className="border-t border-border bg-muted/30">
      <div className="mx-auto max-w-[80rem] px-5 py-16">
        <div className="flex items-end justify-between mb-8">
          <div>
            <p className="text-sm font-semibold uppercase tracking-wider text-accent">Latest Updates</p>
            <h2 className="mt-1 font-display text-3xl font-bold tracking-tight">News & Announcements</h2>
          </div>
          <Link to="/news" className="text-sm font-medium text-primary hover:underline hidden sm:block">View all news →</Link>
        </div>
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {posts.map((p) => {
            const imgUrl = p.featuredImage ? pb.files.getURL(p, p.featuredImage, { thumb: "400x280" }) : null;
            const cat = p.expand?.category;
            const isArticle = p.type === "article";
            return (
              <Link
                key={p.id}
                to={`/${isArticle ? "articles" : "news"}/${p.id}`}
                className="group flex flex-col rounded-2xl border border-border bg-card overflow-hidden shadow-sm hover:-translate-y-1 hover:shadow-md transition"
              >
                <div className="relative h-40 bg-muted overflow-hidden">
                  {imgUrl
                    ? <img src={imgUrl} alt={p.title} className="h-full w-full object-cover transition group-hover:scale-105" />
                    : <div className="h-full flex items-center justify-center bg-primary/5"><MapPinned className="h-8 w-8 text-primary/20" /></div>}
                  {cat && (
                    <span className="absolute top-2 left-2 rounded-full px-2 py-0.5 text-[10px] font-semibold text-white" style={{ background: cat.color || "#2563eb" }}>{cat.name}</span>
                  )}
                </div>
                <div className="p-4 flex flex-col flex-1">
                  <h3 className="font-semibold text-sm line-clamp-2 group-hover:text-primary transition flex-1">{p.title}</h3>
                  <p className="text-xs text-muted-foreground mt-2">
                    {new Date(p.publishedAt || p.created).toLocaleDateString("en-GH", { day: "numeric", month: "short", year: "numeric" })}
                  </p>
                </div>
              </Link>
            );
          })}
        </div>
        <div className="mt-6 text-center sm:hidden">
          <Link to="/news" className="text-sm font-medium text-primary hover:underline">View all news →</Link>
        </div>
      </div>
    </section>
  );
}

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-border last:border-0">
      <button
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between gap-4 py-5 text-left"
      >
        <span className="font-medium text-foreground">{q}</span>
        {open ? <ChevronUp className="h-4 w-4 shrink-0 text-primary" /> : <ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground" />}
      </button>
      {open && (
        <p className="pb-5 text-sm leading-relaxed text-muted-foreground">{a}</p>
      )}
    </div>
  );
}



export default function LandingPage() {
  const { stats: liveStats, error: statsError } = useLiveStats();
  return (
    <div className="min-h-screen bg-background">
      <PublicNav />

      {/* Hero */}
      <section className="relative flex min-h-[100dvh] items-center overflow-hidden pt-16">
        <div className="absolute inset-0">
          <img src={HERO} alt="Aerial view of Techiman North District farmland parcels" className="h-full w-full object-cover" />
          <div className="absolute inset-0 bg-gradient-to-r from-primary via-primary/90 to-primary/40" />
        </div>
        <div className="relative mx-auto max-w-[80rem] px-5 py-16">
          <div className="max-w-2xl">
            <motion.span
              initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}
              className="inline-flex items-center gap-2 rounded-full border border-accent/40 bg-accent/15 px-3 py-1 text-xs font-semibold text-accent"
            >
              <span className="h-1.5 w-1.5 rounded-full bg-accent" /> Techiman North District Assembly — Official Portal
            </motion.span>
            <motion.h1
              initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.05 }}
              className="mt-5 font-display text-4xl font-extrabold leading-[1.05] tracking-tight text-white text-balance sm:text-5xl lg:text-6xl"
            >
              Secure Digital Land Administration for Techiman North
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.12 }}
              className="mt-5 max-w-xl text-lg text-primary-foreground/80"
            >
              The official land registration, survey, and title management platform for the Techiman North District Assembly. Serving five area councils with transparent, secure, and efficient land administration.
            </motion.p>
            <motion.div
              initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.2 }}
              className="mt-8 flex flex-wrap gap-3"
            >
              <Button asChild size="lg" className="bg-accent text-accent-foreground hover:bg-accent/90">
                <Link to="/auth">Staff Portal Login <ArrowRight className="ml-1 h-4 w-4" /></Link>
              </Button>
              <Button asChild size="lg" variant="outline" className="border-white/30 bg-white/5 text-white hover:bg-white/15 hover:text-white">
                <a href="#how-it-works">How It Works</a>
              </Button>
            </motion.div>
            <div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-primary-foreground/70">
              {["Ghana Card Verified", "AES-256 Encrypted", "Audit Logged", "Act 1036 Compliant"].map((t) => (
                <span key={t} className="inline-flex items-center gap-1.5">
                  <CheckCircle2 className="h-4 w-4 text-accent" /> {t}
                </span>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Stats Band — live data from PocketBase */}
      <div className="border-y border-border bg-card">
        <div className="mx-auto max-w-[80rem] px-5">
          <div className="grid grid-cols-2 gap-px bg-border lg:grid-cols-4">
            {STATS_STATIC.map((s, i) => {
              const raw = liveStats[s.key];
              const isLoaded = raw !== null && raw !== undefined;
              return (
                <motion.div
                  key={s.label}
                  initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: i * 0.08 }}
                  className="flex flex-col items-center gap-2 bg-card px-6 py-10 text-center"
                >
                  <span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                    <s.icon className="h-5 w-5" strokeWidth={1.8} />
                  </span>
                  <p className="font-display text-3xl font-extrabold text-primary">
                    {isLoaded
                      ? <AnimatedCount value={raw} suffix={s.suffix} />
                      : statsError
                        ? <span className="text-muted-foreground/60 text-base font-semibold">Unavailable</span>
                        : <span className="opacity-40">—</span>
                    }
                  </p>
                  <p className="text-sm text-muted-foreground">{s.label}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Services */}
      <section id="services" className="mx-auto max-w-[80rem] px-5 py-20">
        <div className="text-center max-w-2xl mx-auto mb-12">
          <p className="text-sm font-semibold uppercase tracking-wider text-accent">Our Services</p>
          <h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">
            Comprehensive Land Administration Services
          </h2>
          <p className="mt-3 text-muted-foreground">
            Everything you need to manage land ownership, registration, and documentation in one integrated platform.
          </p>
        </div>
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {SERVICES.map((s, i) => (
            <motion.div
              key={s.title}
              initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }}
              transition={{ duration: 0.4, delay: (i % 3) * 0.06 }}
              className="group rounded-2xl border border-border bg-card p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md hover:border-primary/30"
            >
              <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary transition group-hover:bg-primary group-hover:text-primary-foreground">
                <s.icon className="h-5 w-5" strokeWidth={1.8} />
              </span>
              <h3 className="mt-4 font-display text-base font-semibold">{s.title}</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{s.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Platform Features */}
      <section id="features" className="bg-card">
        <div className="mx-auto max-w-[80rem] px-5 py-20">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <p className="text-sm font-semibold uppercase tracking-wider text-accent">Platform Features</p>
            <h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">
              Everything the Registry Does — In One Place
            </h2>
            <p className="mt-3 text-muted-foreground">
              A complete digital land administration toolkit built for transparency, security, and efficiency across all Techiman North Area Councils.
            </p>
          </div>
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.4, delay: (i % 4) * 0.06 }}
                className="group rounded-2xl border border-border bg-background p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md hover:border-primary/30"
              >
                <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary transition group-hover:bg-primary group-hover:text-primary-foreground">
                  <f.icon className="h-5 w-5" strokeWidth={1.8} />
                </span>
                <h3 className="mt-4 font-display text-base font-semibold">{f.title}</h3>
                <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="border-y border-border bg-secondary/40">
        <div className="mx-auto max-w-[80rem] px-5 py-20">
          <div className="text-center max-w-2xl mx-auto mb-14">
            <p className="text-sm font-semibold uppercase tracking-wider text-accent">Step by Step</p>
            <h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">How Land Registration Works</h2>
            <p className="mt-3 text-muted-foreground">Follow these steps to successfully register your land and receive an official title certificate.</p>
          </div>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {STEPS.map((step, i) => (
              <motion.div
                key={step.num}
                initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.07 }}
                className="relative"
              >
                <div className="rounded-2xl border border-border bg-card p-6 shadow-sm h-full">
                  <div className="flex items-center gap-4 mb-4">
                    <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-primary font-display text-lg font-extrabold text-primary-foreground">
                      {step.num}
                    </span>
                    {i < STEPS.length - 1 && (
                      <div className="hidden lg:block h-0.5 flex-1 bg-primary/20" />
                    )}
                  </div>
                  <h3 className="font-display text-base font-semibold">{step.title}</h3>
                  <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{step.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* About / Photo section */}
      <section className="mx-auto max-w-[80rem] px-5 py-20">
        <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
          <div className="relative">
            <img src={SURVEY} alt="Land surveyor at work in Techiman North District" className="w-full rounded-3xl object-cover shadow-lg" />
            <div className="absolute -bottom-6 -right-4 hidden rounded-2xl border border-border bg-card p-5 shadow-xl sm:block">
              <div className="flex items-center gap-3">
                <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent/15">
                  <Award className="h-5 w-5 text-blue-600" />
                </span>
                <div>
                  <p className="font-display text-base font-bold text-foreground">Act 1036 Compliant</p>
                  <p className="text-xs text-muted-foreground">Ghana Land Act 2020</p>
                </div>
              </div>
            </div>
          </div>
          <div>
            <p className="text-sm font-semibold uppercase tracking-wider text-accent">About the System</p>
            <h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">
              Built for Transparent, Accountable Land Governance
            </h2>
            <p className="mt-4 text-muted-foreground leading-relaxed">
              The Techiman North District Land Registry System is the official digital platform for managing all land administration activities within the district. Built in compliance with the Land Registration Act 2020 (Act 1036), it brings together registration, survey, documentation, and payment workflows under one secure platform.
            </p>
            <p className="mt-3 text-muted-foreground leading-relaxed">
              Seven specialized portals serve different stakeholders — from Physical Planning Officers reviewing applications, to Surveyors capturing boundary data, to Finance Officers processing payments — all with strict role-based access controls and immutable audit trails.
            </p>
            <ul className="mt-6 space-y-3">
              {[
                "Covers all 5 Area Councils in the district",
                "Real-time notifications and SMS updates",
                "Full Arabic and English support",
                "Integrated payment processing",
                "Complete ownership transfer workflow",
              ].map((item) => (
                <li key={item} className="flex items-center gap-2.5 text-sm">
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-primary" />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Security */}
      <section id="security" className="border-y border-border bg-primary">
        <div className="mx-auto max-w-[80rem] px-5 py-20">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <p className="text-sm font-semibold uppercase tracking-wider text-accent">Security & Compliance</p>
            <h2 className="mt-2 font-display text-3xl font-bold tracking-tight text-white sm:text-4xl">
              Protected by Enterprise-Grade Security
            </h2>
            <p className="mt-3 text-primary-foreground/75">
              Every record is protected by multiple layers of security and compliant with Ghanaian law.
            </p>
          </div>
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {COMPLIANCE.map((c, i) => (
              <motion.div
                key={c.title}
                initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur"
              >
                <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-accent/20 text-accent">
                  <c.icon className="h-5 w-5" strokeWidth={1.8} />
                </span>
                <h3 className="mt-4 font-display text-base font-semibold text-white">{c.title}</h3>
                <p className="mt-1.5 text-sm leading-relaxed text-primary-foreground/70">{c.body}</p>
              </motion.div>
            ))}
          </div>
          <div className="mt-10 text-center">
            <p className="text-sm text-primary-foreground/60">
              Compliant with Ghana's Land Act (Act 1036) · Data Protection Act (Act 843) · Cybersecurity Act (Act 1038)
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="mx-auto max-w-[80rem] px-5 py-20">
        <div className="grid gap-12 lg:grid-cols-[1fr_1.4fr]">
          <div>
            <p className="text-sm font-semibold uppercase tracking-wider text-accent">FAQ</p>
            <h2 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Frequently Asked Questions</h2>
            <p className="mt-3 text-muted-foreground">Have a question not listed here? Contact the Techiman North District Assembly office.</p>
            <div className="mt-8 space-y-4">
              <div className="flex items-start gap-3">
                <Phone className="h-4 w-4 mt-0.5 shrink-0 text-primary" />
                <div>
                  <p className="text-sm font-medium">District Office</p>
                  <p className="text-sm text-muted-foreground">+233 XX XXX XXXX</p>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <Mail className="h-4 w-4 mt-0.5 shrink-0 text-primary" />
                <div>
                  <p className="text-sm font-medium">Email</p>
                  <p className="text-sm text-muted-foreground">info@tenda.gov.gh</p>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <MapPin className="h-4 w-4 mt-0.5 shrink-0 text-primary" />
                <div>
                  <p className="text-sm font-medium">Office Location</p>
                  <p className="text-sm text-muted-foreground">Techiman North District Assembly, Tuobodom, Bono East Region</p>
                </div>
              </div>
            </div>
            <div className="mt-8 rounded-2xl border border-border bg-card p-6">
              <div className="flex items-center gap-3 mb-3">
                <img src={CITIZEN} alt="Land certificate holder" className="h-14 w-14 rounded-full object-cover" />
                <div>
                  <p className="text-sm font-semibold">"Fast and transparent"</p>
                  <p className="text-xs text-muted-foreground">District Land Registrar</p>
                </div>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                "The system has transformed how we handle land records — everything is searchable, auditable, and secure."
              </p>
            </div>
          </div>
          <div className="divide-y divide-border rounded-2xl border border-border bg-card px-6">
            {FAQS.map((faq) => (
              <FAQItem key={faq.q} q={faq.q} a={faq.a} />
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-gradient-to-br from-primary to-primary/90">
        <div className="mx-auto max-w-[80rem] px-5 py-16 text-center">
          <h2 className="font-display text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Ready to Manage Land Records Digitally?
          </h2>
          <p className="mx-auto mt-3 max-w-xl text-primary-foreground/80">
            Access your role-based portal to register, manage, and verify land records across all Techiman North Area Councils.
          </p>
          <div className="mt-7 flex flex-wrap justify-center gap-3">
            <Button asChild size="lg" className="bg-accent text-accent-foreground hover:bg-accent/90">
              <Link to="/auth">Sign in to Portal <ArrowRight className="ml-1 h-4 w-4" /></Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="border-white/30 bg-white/5 text-white hover:bg-white/15 hover:text-white">
              <a href="#services">Learn more</a>
            </Button>
          </div>
        </div>
      </section>

      <LatestNews />

      {/* Spacer to prevent content overlap with sticky footer */}
      <div className="h-12" />
      <StickyFooter />
      <NewsFlash />
    </div>
  );
}
